export interface Envelope {
	data: string
	signature: string
}

export interface CheckoutRequestPayload {
	version: number
	public_key: string
	action: string
	amount: number
	currency: string
	description: string
	order_id: string
	rro_info?: object
	expired_date?: string
	language?: string
	paytypes?: string
	result_url?: string
	server_url?: string
	verifycode?: string
	split_rules?: string
	sender_address?: string
	sender_city?: string
	sender_country_code?: string
	sender_first_name?: string
	sender_last_name?: string
	sender_postal_code?: string
	subscribe?: string
	subscribe_date_start?: string
	subscribe_periodicity?: string
	customer?: string
	recurringbytoken?: string
	customer_user_id?: string
	dae?: string
	info?: string
	product_category?: string
	product_description?: string
	product_name?: string
	product_url?: string
}

export interface CheckoutCallbackPayload {
	acq_id: number
	action: string
	agent_commission: number
	amount: number
	amount_bonus: number
	amount_credit: number
	amount_debit: number
	authcode_credit: string
	authcode_debit: string
	card_token: string
	commission_credit: number
	commission_debit: number
	completion_date: string
	create_date: string
	currency: string
	currency_credit: string
	currency_debit: string
	customer: string
	description: string
	end_date: string
	err_code: string
	err_description: string
	info: string
	ip: string
	is_3ds: boolean
	_order_id: string
	mpi_eci: number
	order_id: string
	payment_id: number
	paytype: string
	public_key: string
	receiver_commission: number
	redirect_to: string
	refund_date_last: string
	rrn_credit: string
	rrn_debit: string
	sender_bonus: number
	sender_card_bank: string
	sender_card_country: string
	sender_card_mask2: string
	sender_iban: string
	sender_card_type: string
	sender_commission: number
	sender_first_name: string
	sender_last_name: string
	sender_phone: string
	status: string
	wait_reserve_status?: string
	token: string
	type: string
	version: number
	err_erc: string
	product_category: string
	product_description: string
	product_name: string
	product_url: string
	refund_amount: number
	verifycode?: string
}

export interface PaymentStatusRequestPayload {
	version: number
	public_key: string
	action: string
	order_id: string
}

export interface PaymentStatusResponsePayload {
	version: number
	public_key: string
	action: string
	acq_id: number
	agent_commission: number
	amount: number
	amount_bonus: number
	amount_credit: number
	amount_debit: number
	authcode_credit: string
	authcode_debit: string
	bonus_procent: number
	bonus_type: string
	card_token: string
	commission_credit: number
	commission_debit: number
	confirm_phone: string
	create_date: string
	currency: string
	currency_credit: string
	currency_debit: string
	description: string
	end_date: string
	info: string
	ip: string
	is_3ds: boolean
	language: string
	_order_id: string
	moment_part: string
	mpi_eci: number
	order_id: string
	payment_id: number
	paytype: string
	receiver_commission: number
	result: string
	rrn_credit: string
	rrn_debit: string
	sender_bonus: number
	sender_card_bank: string
	sender_card_country: string
	sender_card_mask2: string
	sender_iban: string
	sender_card_type: string
	sender_commission: number
	sender_first_name: string
	sender_last_name: string
	sender_phone: string
	status: string
	wait_reserve_status?: string
	transaction_id: number
	type: string
}
