import { z } from 'zod'

import {
	LiqPayActionSchema,
	LiqPayCurrencySchema,
	LiqPayMpiEciSchema,
	LiqPayPaymentStatusSchema,
	LiqPayPaytypeSchema,
} from '../common/enums'

export const LiqPayCheckoutCallbackSchema = z.object({
	acq_id: z.number(),
	action: LiqPayActionSchema,
	agent_commission: z.number(),
	amount: z.number(),
	amount_bonus: z.number(),
	amount_credit: z.number(),
	amount_debit: z.number(),
	authcode_credit: z.string(),
	authcode_debit: z.string(),
	card_token: z.string(),
	commission_credit: z.number(),
	commission_debit: z.number(),
	completion_date: z.string(),
	create_date: z.string(),
	currency: LiqPayCurrencySchema,
	currency_credit: LiqPayCurrencySchema,
	currency_debit: LiqPayCurrencySchema,
	customer: z.string().max(100),
	description: z.string(),
	end_date: z.string(),
	err_code: z.string(),
	err_description: z.string(),
	info: z.string(),
	ip: z.string(),
	is_3ds: z.boolean(),
	liqpay_order_id: z.string(),
	mpi_eci: LiqPayMpiEciSchema,
	order_id: z.string(),
	payment_id: z.number(),
	paytype: LiqPayPaytypeSchema,
	public_key: z.string(),
	receiver_commission: z.number(),
	redirect_to: z.string(),
	refund_date_last: z.string(),
	rrn_credit: z.string(),
	rrn_debit: z.string(),
	sender_bonus: z.number(),
	sender_card_bank: z.string(),
	sender_card_country: z.string(),
	sender_card_mask2: z.string(),
	sender_iban: z.string(),
	sender_card_type: z.string(),
	sender_commission: z.number(),
	sender_first_name: z.string(),
	sender_last_name: z.string(),
	sender_phone: z.string(),
	status: LiqPayPaymentStatusSchema,
	wait_reserve_status: z.literal('true').optional(),
	token: z.string(),
	type: z.string(),
	version: z.literal(7),
	err_erc: z.string(),
	product_category: z.string(),
	product_description: z.string(),
	product_name: z.string(),
	product_url: z.string(),
	refund_amount: z.number(),
	verifycode: z.literal('Y').optional(),
})

export type LiqPayCheckoutCallback = z.infer<
	typeof LiqPayCheckoutCallbackSchema
>
