import { z } from 'zod'

import {
	LiqPayActionSchema,
	LiqPayBonusTypeSchema,
	LiqPayCurrencySchema,
	LiqPayLanguageSchema,
	LiqPayMpiEciSchema,
	LiqPayPaymentStatusSchema,
	LiqPayPaytypeSchema,
	LiqPayRequestResultSchema,
} from '../common/enums'

export const LiqPayPaymentStatusResponseSchema = z.object({
	acq_id: z.number(),
	action: LiqPayActionSchema,
	agent_commission: z.number(),
	amount: z.number(),
	amount_bonus: z.number(),
	amount_credit: z.number(),
	amount_debit: z.number(),
	authcode_credit: z.string(),
	authcode_debit: z.string(),
	bonus_procent: z.number(),
	bonus_type: LiqPayBonusTypeSchema,
	card_token: z.string(),
	commission_credit: z.number(),
	commission_debit: z.number(),
	confirm_phone: z.string(),
	create_date: z.string(),
	currency: LiqPayCurrencySchema,
	currency_credit: LiqPayCurrencySchema,
	currency_debit: LiqPayCurrencySchema,
	description: z.string(),
	end_date: z.string(),
	info: z.string(),
	ip: z.string(),
	is_3ds: z.boolean(),
	language: LiqPayLanguageSchema,
	liqpay_order_id: z.string(),
	moment_part: z.string(),
	mpi_eci: LiqPayMpiEciSchema,
	order_id: z.string(),
	payment_id: z.number(),
	paytype: LiqPayPaytypeSchema,
	public_key: z.string(),
	receiver_commission: z.number(),
	result: LiqPayRequestResultSchema,
	rrn_credit: z.string(),
	rrn_debit: z.string(),
	sender_bonus: z.number(),
	sender_card_bank: z.string(),
	sender_card_country: z.string(),
	sender_card_mask2: z.string(),
	sender_iban: z.string(),
	sender_card_type: z.string(),
	sender_commission: z.number(),
	sender_first_name: z.string(),
	sender_last_name: z.string(),
	sender_phone: z.string(),
	status: LiqPayPaymentStatusSchema,
	wait_reserve_status: z.literal('true').optional(),
	transaction_id: z.number(),
	type: z.string(),
	version: z.literal(7),
})

export type LiqPayPaymentStatusResponse = z.infer<
	typeof LiqPayPaymentStatusResponseSchema
>
